name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - review_requested
  schedule:
    # https://crontab.guru/#0_11_*_*_*
    - cron: 0 11 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: zcong1993/setup-timezone@v1.0
        with:
          timezone: 'Asia/Tokyo'
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
