name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - review_requested
  schedule:
    # https://crontab.guru/#0_2_*_*_*
    # This is UTC. It's 11 in JST
    - cron: 0 2 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
